## Tests on the submodules created

In [1]:
from src import build_wb_datasets as Wbuild

In [2]:
data_tuple = Wbuild.build_wb_dataset(2000, 2020)

Fetching World Bank country list...
Fetching GFDD.DI.09 (Life insurance premium / GDP)...
Fetching GFDD.DI.10 (Non-life insurance premium / GDP)...
Fetching NY.GDP.MKTP.CD (GDP, current US$)...
Fetching SP.POP.TOTL (Population, total)...

In [ ]:
data_tuple[0].head()

,country,iso3,region,income_level,year,type,penetration,population,gdp,premium,premium_per_capita,source
0,Aruba,ABW,Latin America & Caribbean,HIC,2000,Life,NaN,90588.0,1.873453e+09,NaN,NaN,World Bank
1,Afghanistan,AFG,"Middle East, North Africa, Afghanistan & Pakistan",LIC,2000,Life,NaN,20130327.0,3.521418e+09,NaN,NaN,World Bank
2,Angola,AGO,Sub-Saharan Africa,LMC,2000,Life,0.012358,16194869.0,9.129595e+09,1.128272e+06,0.069668,World Bank
3,Albania,ALB,Europe & Central Asia,UMC,2000,Life,0.001720,3089027.0,3.584570e+09,6.166895e+04,0.019964,World Bank
4,Andorra,AND,Europe & Central Asia,HIC,2000,Life,NaN,65685.0,1.432606e+09,NaN,NaN,World Bank

In [4]:
data_tuple[1].head()

,country,iso3,region,income_level,year,gdp,population
0,Aruba,ABW,Latin America & Caribbean,HIC,2000,1.873453e+09,90588.0
1,Aruba,ABW,Latin America & Caribbean,HIC,2001,1.896457e+09,91439.0
2,Aruba,ABW,Latin America & Caribbean,HIC,2002,1.961844e+09,92074.0
3,Aruba,ABW,Latin America & Caribbean,HIC,2003,2.044112e+09,93128.0
4,Aruba,ABW,Latin America & Caribbean,HIC,2004,2.254831e+09,95138.0

In [5]:
data_tuple[0].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8988 entries, 0 to 8987
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   country             8988 non-null   object
 1   iso3                8988 non-null   object
 2   region              8988 non-null   object
 3   income_level        8988 non-null   object
 4   year                8988 non-null   int64
 5   type                8988 non-null   object
 6   penetration         6363 non-null   float64
 7   population          8988 non-null   float64
 8   gdp                 8756 non-null   float64
 9   premium             6343 non-null   float64
 10  premium_per_capita  6343 non-null   float64
 11  source              8988 non-null   object
dtypes: float64(5), int64(1), object(6)
memory usage: 842.8+ KB

In [6]:
data_tuple[1].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4557 entries, 0 to 4556
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   country       4557 non-null   object
 1   iso3          4557 non-null   object
 2   region        4557 non-null   object
 3   income_level  4557 non-null   object
 4   year          4557 non-null   int64
 5   gdp           4419 non-null   float64
 6   population    4557 non-null   float64
dtypes: float64(2), int64(1), object(4)
memory usage: 249.3+ KB

In [7]:
Wbuild.to_wide(data_tuple[0]).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4494 entries, 0 to 4493
Data columns (total 18 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   iso3                        4494 non-null   object
 1   year                        4494 non-null   int64
 2   country                     4494 non-null   object
 3   region                      4494 non-null   object
 4   income_level                4494 non-null   object
 5   population                  4494 non-null   float64
 6   gdp                         4378 non-null   float64
 7   life                        3100 non-null   float64
 8   nonlife                     3263 non-null   float64
 9   premium_life                3090 non-null   float64
 10  premium_nonlife             3253 non-null   float64
 11  premium_per_capita_life     3090 non-null   float64
 12  premium_per_capita_nonlife  3253 non-null   float64
 13  total                       3264 non-null   float64
 14  premium_total               3254 non-null   float64
 15  premium_per_capita_total    3254 non-null   float64
 16  share_life                  3090 non-null   float64
 17  share_nonlife               3253 non-null   float64
dtypes: float64(13), int64(1), object(4)
memory usage: 632.1+ KB