## Tests on the submodules created

### World bank dataset builder

In [1]:
from src import build_wb_datasets as Wbuild

In [2]:
data_tuple = Wbuild.build_wb_dataset(2000, 2020)

Fetching World Bank country list...
Fetching GFDD.DI.09 (Life insurance premium / GDP)...
Fetching GFDD.DI.10 (Non-life insurance premium / GDP)...
Fetching NY.GDP.MKTP.CD (GDP, current US$)...
Fetching SP.POP.TOTL (Population, total)...

In [3]:
data_tuple[0].head()

,country,iso3,region,income_level,year,type,penetration,population,gdp,premium,premium_per_capita,source
0,Aruba,ABW,Latin America & Caribbean,HIC,2000,Life,NaN,90588.0,1.873453e+09,NaN,NaN,World Bank
1,Afghanistan,AFG,"Middle East, North Africa, Afghanistan & Pakistan",LIC,2000,Life,NaN,20130327.0,3.521418e+09,NaN,NaN,World Bank
2,Angola,AGO,Sub-Saharan Africa,LMC,2000,Life,0.012358,16194869.0,9.129595e+09,1.128272e+06,0.069668,World Bank
3,Albania,ALB,Europe & Central Asia,UMC,2000,Life,0.001720,3089027.0,3.584570e+09,6.166895e+04,0.019964,World Bank
4,Andorra,AND,Europe & Central Asia,HIC,2000,Life,NaN,65685.0,1.432606e+09,NaN,NaN,World Bank

In [4]:
data_tuple[1].head()

,country,iso3,region,income_level,year,gdp,population
0,Aruba,ABW,Latin America & Caribbean,HIC,2000,1.873453e+09,90588.0
1,Aruba,ABW,Latin America & Caribbean,HIC,2001,1.896457e+09,91439.0
2,Aruba,ABW,Latin America & Caribbean,HIC,2002,1.961844e+09,92074.0
3,Aruba,ABW,Latin America & Caribbean,HIC,2003,2.044112e+09,93128.0
4,Aruba,ABW,Latin America & Caribbean,HIC,2004,2.254831e+09,95138.0

In [5]:
data_tuple[0].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8988 entries, 0 to 8987
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   country             8988 non-null   object
 1   iso3                8988 non-null   object
 2   region              8988 non-null   object
 3   income_level        8988 non-null   object
 4   year                8988 non-null   int64
 5   type                8988 non-null   object
 6   penetration         6363 non-null   float64
 7   population          8988 non-null   float64
 8   gdp                 8756 non-null   float64
 9   premium             6343 non-null   float64
 10  premium_per_capita  6343 non-null   float64
 11  source              8988 non-null   object
dtypes: float64(5), int64(1), object(6)
memory usage: 842.8+ KB

In [6]:
data_tuple[1].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4557 entries, 0 to 4556
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   country       4557 non-null   object
 1   iso3          4557 non-null   object
 2   region        4557 non-null   object
 3   income_level  4557 non-null   object
 4   year          4557 non-null   int64
 5   gdp           4419 non-null   float64
 6   population    4557 non-null   float64
dtypes: float64(2), int64(1), object(4)
memory usage: 249.3+ KB

In [7]:
Wbuild.to_wide(data_tuple[0]).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4494 entries, 0 to 4493
Data columns (total 18 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   iso3                        4494 non-null   object
 1   year                        4494 non-null   int64
 2   country                     4494 non-null   object
 3   region                      4494 non-null   object
 4   income_level                4494 non-null   object
 5   population                  4494 non-null   float64
 6   gdp                         4378 non-null   float64
 7   life                        3100 non-null   float64
 8   nonlife                     3263 non-null   float64
 9   premium_life                3090 non-null   float64
 10  premium_nonlife             3253 non-null   float64
 11  premium_per_capita_life     3090 non-null   float64
 12  premium_per_capita_nonlife  3253 non-null   float64
 13  total                       3264 non-null   float64
 14  premium_total               3254 non-null   float64
 15  premium_per_capita_total    3254 non-null   float64
 16  share_life                  3090 non-null   float64
 17  share_nonlife               3253 non-null   float64
dtypes: float64(13), int64(1), object(4)
memory usage: 632.1+ KB

### Allianz reports extractor

In [8]:
from src import extract_allianz as Extract

* Example with 2 segments format

In [9]:
from pathlib import Path
notebook_dir = Path("C:/Users/simar/OneDrive/Bureau/Persos/LinkedIn/Insurance-penetration/RDataLab-InsuranceDataApp")  # à adapter
path = notebook_dir.parent / "Allianz-Insurance Reports"/"Global-Insurance-Report-2022.pdf"

In [10]:
path

WindowsPath('C:/Users/simar/OneDrive/Bureau/Persos/LinkedIn/Insurance-penetration/Allianz-Insurance Reports/Global-Insurance-Report-2022.pdf')

In [11]:
path.name

'Global-Insurance-Report-2022.pdf'

In [12]:
Report = Extract.extract_report(path)

In [13]:
Report[0].head(10)

,country_raw,year,pc_penetration,life_penetration,health_penetration,pc_premium_eur_bn,life_premium_eur_bn,health_premium_eur_bn,source_file
0,Argentina,2021,2.6,0.4,None,9.4,1.4,None,Global-Insurance-Report-2022.pdf
1,Australia,2021,2.4,1.0,None,32.1,13.7,None,Global-Insurance-Report-2022.pdf
2,Austria,2021,2.6,1.3,None,10.7,5.4,None,Global-Insurance-Report-2022.pdf
3,Bahrain,2021,1.1,0.6,None,0.3,0.2,None,Global-Insurance-Report-2022.pdf
4,Belgium,2021,2.1,3.1,None,10.4,15.5,None,Global-Insurance-Report-2022.pdf
5,Brazil,2021,1.1,0.5,None,15.3,6.7,None,Global-Insurance-Report-2022.pdf
6,Bulgaria,2021,2.1,0.4,None,1.4,0.2,None,Global-Insurance-Report-2022.pdf
7,Canada,2021,3.2,3.4,None,53.7,56.0,None,Global-Insurance-Report-2022.pdf
8,Chile,2021,1.6,1.7,None,3.8,4.2,None,Global-Insurance-Report-2022.pdf
9,China,2021,1.1,2.1,None,177.7,325.2,None,Global-Insurance-Report-2022.pdf

In [14]:
Report[2]

'Allianz Research\nAppendix\nAppendix A: P&C insurance market Life insurance market1\n2021 KPIs total 2021 per capita as a % of GDP total 2021 per capita as a % of GDP\nin EUR bn yoy in % in EUR in EUR bn yoy in % in EUR\nArgentina 9.4 52.4 207 2.6 1.4 49.4 32 0.4\nAustralia 32.1 11.2 1,245 2.4 13.7 0.8 529 1.0\nAustria 10.7 4.7 1,186 2.6 5.4 0.6 594 1.3\nBahrain 0.3 -0.7 196 1.1 0.2 23.3 103 0.6\nBelgium 10.4 3.0 898 2.1 15.5 3.2 1,336 3.1\nBrazil 15.3 13.3 72 1.1 6.7 14.2 31 0.5\nBulgaria 1.4 8.4 198 2.1 0.2 42.8 36 0.4\nCanada 53.7 5.6 1,410 3.2 56.0 6.4 1,470 3.4\nChile 3.8 12.6 200 1.6 4.2 3.5 217 1.7\nChina 177.7 -1.7 123 1.1 325.2 -1.7 225 2.1\nColombia 4.4 20.1 85 1.8 3.6 15.6 70 1.5\nCroatia 1.1 12.8 265 1.9 0.4 9.4 94 0.7\nCzech Republic 4.9 8.4 461 2.0 1.8 1.1 171 0.7\nDenmark 9.8 3.9 1,680 3.0 23.8 6.0 4,091 7.3\nEgypt 1.3 40.0 13 0.4 1.6 26.4 15 0.5\nFinland 4.2 2.8 755 1.7 5.4 35.7 975 2.2\nFrance 75.2 3.2 1,150 3.0 115.7 -0.5 1,769 4.6\nGermany 78.6 2.4 937 2.2 97.2 -1.4 1,158 2.7\nGreece 2.3 5.7 218 1.3 2.4 13.8 228 1.3\nHong Kong 3.6 5.8 470 1.1 58.0 -1.3 7,684 17.7\nHungary 2.0 7.7 202 1.3 1.6 13.4 168 1.1\nIndia 17.3 2.2 12 0.6 81.5 9.7 58 3.0\nIndonesia 4.1 -0.7 15 0.4 11.4 14.7 41 1.1\nIreland 4.0 4.3 802 0.9 14.1 6.6 2,838 3.2\nItaly 36.1 2.6 599 2.0 118.1 12.5 1,956 6.6\nJapan 73.0 0.2 579 1.7 229.6 2.9 1,821 5.5\nKazakhstan 0.7 11.7 37 0.4 0.6 60.9 30 0.4\nKenia 0.8 17.0 14 0.9 1.0 24.0 18 1.1\nLaos 0.1 21.1 10 0.5 0.0 25.0 1 0.0\nLebanon 0.7 27.0 97 0.4 0.3 -9.9 48 0.2\nMalaysia 3.6 3.0 111 1.1 9.0 8.0 273 2.8\nMexico 10.6 10.5 81 0.9 12.9 11.0 99 1.2\nMorocco 2.2 8.8 60 2.0 2.2 11.6 58 2.0\nNetherlands 12.9 5.3 754 1.5 12.6 3.1 732 1.5\nNigeria 0.8 36.2 4 0.2 0.6 21.3 3 0.2\nNew Zealand 4.5 7.1 924 2.1 1.8 5.4 360 0.8\nNorway 10.2 7.0 1,860 2.8 13.7 29.3 2,509 3.7\nPakistan 0.5 17.6 2 0.2 1.5 30.1 7 0.6\nPeru 1.7 16.1 50 0.9 1.9 39.8 57 1.0\nPhilippines 1.5 12.6 16 0.5 5.4 25.4 48 1.6\nPoland 10.4 8.8 275 1.8 3.3 6.5 87 0.6\nPortugal 4.6 3.9 451 2.2 7.7 68.5 760 3.7\nRomania 2.1 13.2 108 0.9 0.5 23.6 27 0.2\nRussia 13.2 13.2 91 0.9 5.1 0.1 35 0.4\nSaudi Arabia 3.5 0.8 98 0.5 0.4 28.8 11 0.1\nSingapore 2.5 3.4 431 0.7 30.0 21.5 5,085 8.8\nSlovakia 1.2 -4.0 216 1.2 0.8 -6.2 144 0.8\nSouth Africa 11.1 26.6 184 3.3 37.3 20.1 622 11.2\nSouth Korea 78.5 6.4 1,530 5.2 87.9 -0.6 1,714 5.8\nSpain 28.4 2.7 608 2.3 23.6 7.9 504 1.9\nSri Lanka 0.4 2.9 18 0.5 0.5 21.1 25 0.8\nSweden 7.8 2.6 772 1.5 39.8 33.5 3,916 7.5\nSwitzerland 17.4 2.5 2,000 2.5 23.8 -7.9 2,728 3.3\nTaiwan 8.6 6.6 366 1.3 79.4 -7.6 3,280 11.5\nThailand 7.1 4.7 102 1.7 13.1 0.8 188 3.1\nTurkey 4.1 21.1 48 0.9 1.0 9.7 11 0.2\nUkraine 0.5 -50.0 12 0.3 0.2 0.3 4 0.1\nUnited Arab Emirates 3.7 1.3 374 1.1 2.0 3.6 198 0.6\nUnited Kingdom 81.7 3.9 1,198 2.9 233.2 -2.0 3,419 8.3\nUnited States 685.0 9.7 2,058 3.4 682.5 8.8 2,050 3.4\nVietnam 1.7 17.0 18 0.5 5.6 13.2 57 1.8\n1 Without health\n32'

In [20]:
lines = Report[2].split("\n")
lines[11]

'Bulgaria 1.4 8.4 198 2.1 0.2 42.8 36 0.4'

In [24]:
Extract._split_row_left(lines[11],8)

('Bulgaria', ['1.4', '8.4', '198', '2.1', '0.2', '42.8', '36', '0.4'])

* Example with 3 segments format

In [25]:
path = notebook_dir.parent / "Allianz-Insurance Reports"/"Global-Insurance-Report-2023.pdf"

In [26]:
Report = Extract.extract_report(path)

In [27]:
Report[0].head()

,country_raw,year,pc_penetration,life_penetration,health_penetration,pc_premium_eur_bn,life_premium_eur_bn,health_premium_eur_bn,source_file
0,Argentina,2022,2.3,0.4,0.0,10.2,1.5,0.0,Global-Insurance-Report-2023.pdf
1,Australia,2022,2.4,1.0,1.2,35.4,14.5,17.1,Global-Insurance-Report-2023.pdf
2,Austria,2022,2.5,1.2,0.6,11.4,5.4,2.7,Global-Insurance-Report-2023.pdf
3,Bahrain,2022,1.1,0.3,0.5,0.4,0.1,0.2,Global-Insurance-Report-2023.pdf
4,Belgium,2022,2.0,2.8,0.4,11.0,15.8,2.0,Global-Insurance-Report-2023.pdf

In [29]:
lines = Report[2].split("\n")
lines[10]

'Brazil 21.5 8.7 11.6 1.3 0.5 0.7 100 40 54'

In [30]:
Extract._split_row_left(lines[10],6)

('Brazil', ['21.5', '8.7', '11.6', '1.3', '0.5', '0.7'])